dist: xenial

language: python

script:
  - echo "Womp womp"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "us-east-1"
  app: "COA"
  env: "coa-app"
  bucket_name: "elasticbeanstalk-us-west-2-495512916465"
  on:
    branch: master
